#Ne! Odmítám s tebou mluvit do té doby, ne bude má nemoc vyléèena.
#Vidìl jsi to u nìkdy døíve?
#To jméno jsem neslyšel od doby, co jsem byl malı chlapec.
#Mohu se tì zeptat na pár otázek?
#Za chvíli se tam potkáme.
#Nemoc
#Zdravím náèelníku.
#Morgane.
#Jak mohu vìdìt, e je to to, co Tanner chtìl?
#Kdykoliv vidím Tanu usmívat se, pøitíí se mi a je mi zle od aludku.
#Líbíš se jí. Neproklínala tì, jen s tebou flirtovala.
#Láska? Jak je to moné? Kdy jsem se poprvé oenil, nikdy jsem se takhle necítil.
#Bajari nevypadá pøíliš nemocnì.
#Ne mu tohle ukáu, potøebuji jeho plnou pozornost.
#Pøipomíná mi to, jak kdysi Bobby vyhrál hru na schovávanou. Nikoho nenapadlo hledat ho v hrobì babièky Alice.
#Jak jsi se dostal do chrámu?!
#Zdravím. Jsem Morgane Castillo.
#Bùh kterého Voodoo úctívá nepùsobí moc pøívìtivì.
#Jsi mocnı mu. Tvá nemoc musí bıt opravdu váná, aby tì takto ovlivnila.
#Pravdìpodobnì bych s ní mìl promluvit.
#Kostra
#Øekni jí a jednou provdy odstraní tu kletbu!
#Vskutku. Nikdo na celém svìtì nikdy nebyl tak chorı jako já. Je to kletba.
#Celou dobu se cítím zvláštnì.
#Øekni mi o té kletbì víc. Co tvou nemoc zhoršuje?
#Ha ha ha! U tomu rozumím. Nejsi nemocnı ani prokletı...
#Ne, bylo to odkázáno linii mého otce.
#Kletba
#On a mùj otec byli velmi dobøí pøátelé, ale mùj otec zemøel pøed mnoha lety.
#Snaím se najít nìkoho, kdo bıval blízkım pøítelem Tannera.
#Tanner zemøel pøed lety. Dáš mi to?
#Mohu se tì zeptat na Buckleberryho Tannera?
#Vıchod
#Pøedmìt kterı máš je èástí té stezky.
#Socha
#Dìkuji. Mohl by jsi to pøinést na molo?
#Coe?!
#Drahı Boe, ano! Tanner øekl e je to velmi speciální.
#Dal mu nìkdy nìco do opatrovnictví?
#Otázky
#Tannerovi pøátelé
#No... ano... Hledám to pro nìj.
#Nezaslouila jsem si snad tvojí dùvìru a nepomohla ti?
#Zaèalo to, kdy jsem poprvé potkal Tanu. Musela na mì uvrhnout kletbu.
#Co tì pøimìlo to øíct?
#Mám jasné pravdilo: nech mrtvé na pokoji nebo se obávej jejich hnìvu.
#Snad se Chemi'n dobøe baví.
#Kdykoliv na ní myslím, ztratím chu k jídlu. Jsem prokletı!
#Haha! Díky Morgane.
#Jsi oèividnì zamilovanı do Tany.
#Vypadá, e je jen po uši zamilovanı.
#Chemi'n mi povolil projít.
#Nemìl ádné právo to udìlat.
#Nejsem ten typ eny, kterı dává obìti kamenému bohu.
#To je. Tanner zanechal nápovìdy o kterıch doufal, e jednou budou nalezeny.
#Máš pravdu Morgane. Donesu ti Tannerùv pøedmìt.
#Tanner
#