#Ahoj.
#Je v transu, hledá lék.
#Zkusím se nahoru teleportovat. Hokus pokus!
#Ahoj.
#Vedeš vzrušující ivot...
#Na téhle stranì ostrova jsou stromy hodnì vysoké. Nìkteré mají ke kmenùm pøibité ebøíky.
#Nambi! Nemáš to nikomu øíkat!
#Z tohohle místa mám husí kùi. Je dobøe, e tu nejsem sama.
#Obávám se, e nikoho nepøijme do doby, ne ho Chemi'n vyléèí.
#Je tohle Voodoo vesnice?
#Stromové chıše
#Ahoj. Jsem Morgane. Zajímalo mì, jestli by jsi mi mohl pomoci.
#To znamená, e mùeš do chrámu.
#Yes. And I'm glad I have my back to it.
#Mrazí mì z toho...
#Strom
#Nebudu pouívat jméno, které jsi si pro sebe vybral.
#Myslela jsem, e se Chemi'n snaí vyléèit náèelníka Bajari.
#Chrám
#Tihle uboáci vypadají, jako by tu byli celé dny.
#Netuším jak nahoøe dokáe ít. Z vıšek mám závratì.
#Moná bych je mohla pouít, abych se dostala do horního patra.
#Chemi'n
#Nevíš kde najdu náèelníka Chemi'n?
#Je v transu, hledá lék.
#Vy dva stráíte tento chrám?
#Proè?! Co je zlého na Mighty Konga?
#Mohu s ním mluvit?
#Víš nìco o náèelníkovi Bajari?
#Teï je však v chrámu, nebo se necítí dobøe.
#I kdybych vìdìla, nešla bych tam.
#Jak se dostanu do vyšších pater?
#Ahoj Morgane.
#Dìsivé...
#Myslela jsem, e Chemi'n je nahoøe.
#Proè si jen asi budovali domy ve stromech.
#Samozøejmì.
#Hmm... Abrakadabra! Shazam! Beam me up, Sancha!
#Horní patro
#Jsme tu abychom zabránili komukoliv vstoupit.
#Voodoo vesnice
#Chemi'n mi øekla a ti to ukáu.
#Já jsem Bibli, tohle je Nambi.
#Vidíš? Já ti øíkal, aby jsi to nikomu neøíkala!
#It makes you sound like a party dance.
#Je to jeho jméno nebo povaha?
#Je na plošinách v horním patøe vesnice.
#Bajari
#Vchod do chrámu
#Vyšplhat do vrchního patra
#Stráe mi brání vkroèit do chrámu.
#Je to náš váenı vùdce.
#Ha! Radìji najdu nìjaké schody nebo ebøík.
#Nevíme. Tohle není naše vesnice.
#